from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Tuple
import logging
import math
import numbers

import json

from shapely.geometry import LineString, Point
from shapely.strtree import STRtree

from app.services.reporting_service import reporting_service

try:
    from rtree import index as rtree_index

    _HAS_RTREE = True
except ImportError:  # pragma: no cover
    rtree_index = None
    _HAS_RTREE = False


# Project root: backend/app/services/risk_engine.py → <root>
_PROJECT_ROOT = Path(__file__).resolve().parents[3]
_DUMMY_DATA_PATH = _PROJECT_ROOT / "logic" / "output" / "pune_dummy_safety_data.geojson"

_dummy_geometries: List[LineString] = []
_dummy_properties: List[Dict[str, Any]] = []
_dummy_geom_id_to_index: Dict[int, int] = {}
_dummy_rtree = None
_dummy_strtree = None
_dummy_loaded: bool = False

_time_penalties: Dict[str, float] = {}
_parsed_time_penalties: List[Tuple[int, int, float]] = []
LOGGER = logging.getLogger(__name__)


def _load_dummy_safety_dataset() -> None:
    """
    Load the dummy safety dataset and build a spatial index (R-tree or STRtree).

    This uses the GeoJSON generated by `logic/datagen.py`:
        logic/output/pune_dummy_safety_data.geojson
    """
    global _dummy_loaded, _dummy_geometries, _dummy_properties, _dummy_geom_id_to_index
    global _dummy_rtree, _dummy_strtree, _time_penalties, _parsed_time_penalties

    if _dummy_loaded:
        return

    if not _DUMMY_DATA_PATH.exists():
        raise RuntimeError(
            f"Dummy safety dataset not found at {_DUMMY_DATA_PATH}. "
            "Run logic/datagen.py to generate it."
        )

    with _DUMMY_DATA_PATH.open("r", encoding="utf-8") as f:
        data = json.load(f)

    # Extract spatial features.
    features = data.get("features", [])
    geometries: List[LineString] = []
    properties: List[Dict[str, Any]] = []

    for feature in features:
        geom_dict = feature.get("geometry") or {}
        coords = geom_dict.get("coordinates") or []
        # GeoJSON coordinates are [lon, lat].
        if not coords:
            continue
        line = LineString(coords)
        geometries.append(line)
        properties.append(feature.get("properties") or {})

    _dummy_geometries = geometries
    _dummy_properties = properties
    _dummy_geom_id_to_index = {id(geom): idx for idx, geom in enumerate(_dummy_geometries)}

    # Extract global time penalties for dynamic safety adjustments.
    _time_penalties = data.get("time_penalties", {})
    _parsed_time_penalties = []
    for interval, penalty in _time_penalties.items():
        try:
            start_str, end_str = interval.split("-")
            start_minutes = int(start_str[:2]) * 60 + int(start_str[2:])
            end_minutes = int(end_str[:2]) * 60 + int(end_str[2:])
            _parsed_time_penalties.append(
                (start_minutes, end_minutes, float(penalty))
            )
        except Exception:
            # Ignore malformed entries and continue with valid ones.
            continue

    if _HAS_RTREE and rtree_index is not None:
        idx = rtree_index.Index()
        for i, geom in enumerate(_dummy_geometries):
            idx.insert(i, geom.bounds)
        _dummy_rtree = idx
        _dummy_strtree = None
    else:
        # Fallback to Shapely STRtree when rtree is unavailable.
        _dummy_strtree = STRtree(_dummy_geometries)
        _dummy_rtree = None

    _dummy_loaded = True


def _get_current_time_penalty(current_time: datetime | None = None) -> float:
    """
    Look up the global time-of-day penalty based on the current system time.

    The GeoJSON root defines a `time_penalties` object with keys like "0800-1200".
    """
    if current_time is None:
        current_time = datetime.now()

    if not _parsed_time_penalties:
        return 0.0

    minutes = current_time.hour * 60 + current_time.minute

    for start_minutes, end_minutes, penalty in _parsed_time_penalties:
        if start_minutes <= minutes < end_minutes:
            return penalty

    return 0.0


def _nearest_segment_for_point(lon: float, lat: float) -> Tuple[Dict[str, Any], float]:
    """
    Returns the nearest dummy safety segment (properties + distance) for a WGS84 point.
    """
    if not _dummy_loaded:
        _load_dummy_safety_dataset()

    query_point = Point(lon, lat)

    if _dummy_rtree is not None:
        # R-tree branch: query nearest geometry by bounding box.
        nearest_indices = list(_dummy_rtree.nearest(query_point.bounds, 1))
        if not nearest_indices:
            raise ValueError("No segments found in dummy safety dataset.")
        idx = int(nearest_indices[0])
    else:
        # STRtree branch: query nearest geometry, then resolve its index.
        if _dummy_strtree is None:
            raise ValueError("Spatial index not initialized.")
        nearest_geom = _dummy_strtree.nearest(query_point)
        if isinstance(nearest_geom, numbers.Integral):
            idx = int(nearest_geom)
        else:
            idx = _dummy_geom_id_to_index.get(id(nearest_geom))  # type: ignore[arg-type]
            if idx is None:
                # Fallback equality check when geometry object identity differs.
                for candidate_idx, candidate_geom in enumerate(_dummy_geometries):
                    if candidate_geom.equals(nearest_geom):  # type: ignore[arg-type]
                        idx = candidate_idx
                        break
            if idx is None:
                raise ValueError("Could not resolve nearest segment index.")

    segment_geom = _dummy_geometries[idx]
    segment_props = _dummy_properties[idx]
    # Distance is in degrees; used only as a relative proximity metric here.
    distance_to_query = float(segment_geom.distance(query_point))
    return segment_props, distance_to_query


def _haversine_meters(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    earth_radius_m = 6371000.0
    phi1 = math.radians(lat1)
    phi2 = math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlambda = math.radians(lon2 - lon1)
    a = (
        math.sin(dphi / 2.0) ** 2
        + math.cos(phi1) * math.cos(phi2) * math.sin(dlambda / 2.0) ** 2
    )
    return earth_radius_m * 2.0 * math.atan2(math.sqrt(a), math.sqrt(1.0 - a))


def _normalize_safety_level(score: float) -> str:
    if score >= 70.0:
        return "SAFE"
    if score >= 40.0:
        return "CAUTIOUS"
    return "RISKY"


class RiskEngine:
    def __init__(self):
        # Configuration weights
        self.w_lighting = 0.4
        self.w_crime = 0.4
        self.w_crowd = 0.2
        self.decay_halflife_hours = 24.0
        self.incident_effect_radius_m = 180.0
        self.incident_recency_halflife_hours = 72.0
        self.max_incident_penalty = 45.0
        self.incident_penalty_scale = 26.0

        # Load dummy safety dataset + spatial index on first initialization.
        _load_dummy_safety_dataset()

    def calculate_edge_risk(self, edge_data: Dict, current_time: datetime = None) -> float:
        """
        Calculates a risk score between 0.0 (Safe) and 1.0 (Dangerous)
        """
        if current_time is None:
            current_time = datetime.now()

        # 1. Static Factors
        lighting_risk = edge_data.get('lighting_score', 0.5) # Default to medium if unknown
        base_risk = edge_data.get('base_risk_score', 0.0)

        # 2. Dynamic Factors (Incidents)
        # In a real system, we'd query recent incidents near this edge here
        # For now, we assume edge_data might have a 'recent_incident_severity' field pre-aggregated
        incident_severity = edge_data.get('recent_incident_severity', 0)
        incident_time_hours_ago = edge_data.get('hours_since_incident', 9999)
        
        # Time Decay: Risk = InitialRisk * (0.5 ^ (t / half_life))
        incident_risk = 0.0
        if incident_severity > 0:
            normalized_severity = min(incident_severity / 5.0, 1.0)
            decay_factor = 0.5 ** (incident_time_hours_ago / self.decay_halflife_hours)
            incident_risk = normalized_severity * decay_factor

        # 3. Crowd / Time of Day (Simple heuristic: Night is riskier if lighting is poor)
        hour = current_time.hour
        is_night = hour < 6 or hour > 19
        night_multiplier = 1.2 if is_night and lighting_risk > 0.6 else 1.0

        # Weighted Sum
        total_risk = (
            (lighting_risk * self.w_lighting) +
            (incident_risk * self.w_crime) + 
            (base_risk * 0.2) # Base risk component
        ) * night_multiplier

        return min(max(total_risk, 0.0), 1.0)

    def calculate_segment_risk(self, distance_weight: float, safety_score: float) -> float:
        """
        Calculates a segment-level risk value using the global formula:

            risk = distance_weight + (100 - safety_score)

        where `safety_score` is in the range [0, 100].
        """
        clamped_score = max(0.0, min(100.0, float(safety_score)))
        return float(distance_weight) + (100.0 - clamped_score)

    def map_route_coordinates_to_segments(
        self,
        coordinates: List[Dict[str, float]],
        time_penalty: float,
        incidents: List[Dict[str, Any]] | None = None,
        current_time: datetime | None = None,
    ) -> List[Dict[str, Any]]:
        """
        Map a list of OSRM route coordinates to the closest dummy safety segments.

        `coordinates` is expected to be an ordered list of points:
            [{"lat": <float>, "lon": <float>}, ...]
        representing the decoded OSRM polyline.
        """
        if len(coordinates) < 2:
            return []

        segments: List[Dict[str, Any]] = []

        for i in range(len(coordinates) - 1):
            start = coordinates[i]
            end = coordinates[i + 1]

            mid_lat = (start["lat"] + end["lat"]) / 2.0
            mid_lon = (start["lon"] + end["lon"]) / 2.0

            segment_props, distance_to_query = _nearest_segment_for_point(
                lon=mid_lon,
                lat=mid_lat,
            )
            incident_penalty, incident_density, matched_incidents = (
                self._compute_incident_penalty(
                    lat=mid_lat,
                    lon=mid_lon,
                    incidents=incidents or [],
                    current_time=current_time,
                )
            )

            # Base safety is provided by the dummy dataset; adjust it with
            # the current global time penalty.
            base_safety_score = float(segment_props.get("base_safety_score", 50.0))
            adjusted_safety_score = max(
                0.0,
                min(
                    100.0,
                    base_safety_score - float(time_penalty) - float(incident_penalty),
                ),
            )

            # Distance weight comes from the precomputed segment length in meters.
            segment_distance = float(segment_props.get("distance", 0.0))

            segment_risk = self.calculate_segment_risk(
                distance_weight=segment_distance,
                safety_score=adjusted_safety_score,
            )

            segments.append(
                {
                    "start": start,
                    "end": end,
                    "segment_id": segment_props.get("segment_id"),
                    "safety_level": _normalize_safety_level(adjusted_safety_score),
                    "base_safety_score": base_safety_score,
                    "safety_score": adjusted_safety_score,
                    "incident_density": incident_density,
                    "incident_penalty": incident_penalty,
                    "incident_matches": matched_incidents,
                    "lighting_heuristic": segment_props.get("lighting_heuristic"),
                    "crowd_density": segment_props.get("crowd_density"),
                    "time_penalty": float(time_penalty),
                    "distance": segment_distance,
                    "distance_to_query": distance_to_query,
                    "risk": segment_risk,
                }
            )

        return segments

    async def score_route(self, coordinates: List[Dict[str, float]]) -> Dict[str, Any]:
        """
        Score an OSRM route (list of coordinates) using the dummy safety dataset,
        incorporating global time-of-day penalties.

        Returns per-segment safety metrics and aggregate statistics.
        """
        current_time = datetime.now(timezone.utc)
        current_time_penalty = _get_current_time_penalty(current_time)
        incidents: List[Dict[str, Any]] = []
        try:
            incidents = await reporting_service.get_recent_incidents(lookback_days=30)
        except Exception as exc:
            LOGGER.warning("Incident retrieval failed for dynamic scoring: %s", exc)

        segments = self.map_route_coordinates_to_segments(
            coordinates,
            time_penalty=current_time_penalty,
            incidents=incidents,
            current_time=current_time,
        )

        total_distance = sum(seg.get("distance", 0.0) for seg in segments)
        total_risk = sum(seg.get("risk", 0.0) for seg in segments)
        average_safety_score = (
            sum(seg.get("safety_score", 0.0) for seg in segments) / max(len(segments), 1)
            if segments
            else 0.0
        )

        return {
            "segments": segments,
            "summary": {
                "total_distance": total_distance,
                "total_risk": total_risk,
                "average_safety_score": average_safety_score,
                "applied_incident_count": len(incidents),
            },
        }

    def _compute_incident_penalty(
        self,
        *,
        lat: float,
        lon: float,
        incidents: List[Dict[str, Any]],
        current_time: datetime | None,
    ) -> Tuple[float, float, int]:
        if not incidents:
            return 0.0, 0.0, 0

        now = current_time or datetime.now(timezone.utc)
        weighted_impact = 0.0
        matched = 0

        for incident in incidents:
            incident_lat = _safe_float(incident.get("lat"))
            incident_lon = _safe_float(incident.get("lon"))
            if incident_lat is None or incident_lon is None:
                continue

            distance_m = _haversine_meters(lat, lon, incident_lat, incident_lon)
            if distance_m > self.incident_effect_radius_m:
                continue

            status = str(incident.get("status", "pending")).lower()
            if status in {"rejected", "dismissed", "spam"}:
                continue

            matched += 1
            distance_factor = max(0.0, 1.0 - (distance_m / self.incident_effect_radius_m))
            severity = _safe_float(incident.get("severity")) or 3.0
            severity_factor = max(0.2, min(1.0, severity / 5.0))
            incident_type_factor = self._incident_type_weight(
                str(incident.get("incident_type", ""))
            )
            confidence = _safe_float(incident.get("confidence_score")) or 0.5
            if confidence > 1.0:
                confidence = min(1.0, confidence / 100.0)
            confidence = max(0.1, min(1.0, confidence))
            recency_factor = self._incident_recency_decay(
                incident.get("created_at"), now=now
            )
            status_factor = 1.15 if status == "verified" else 1.0

            weighted_impact += (
                distance_factor
                * severity_factor
                * incident_type_factor
                * confidence
                * recency_factor
                * status_factor
            )

        if matched == 0:
            return 0.0, 0.0, 0

        incident_penalty = min(
            self.max_incident_penalty,
            weighted_impact * self.incident_penalty_scale,
        )
        incident_density = min(100.0, (matched / 6.0) * 100.0)
        return incident_penalty, incident_density, matched

    def _incident_recency_decay(self, created_at: Any, *, now: datetime) -> float:
        incident_time = _safe_datetime(created_at)
        elapsed_hours = max(0.0, (now - incident_time).total_seconds() / 3600.0)
        return 0.5 ** (elapsed_hours / self.incident_recency_halflife_hours)

    def _incident_type_weight(self, incident_type: str) -> float:
        normalized = incident_type.lower()
        if "stalking" in normalized or "harassment" in normalized:
            return 1.0
        if "assault" in normalized or "violence" in normalized:
            return 1.0
        if "suspicious" in normalized:
            return 0.9
        if "lighting" in normalized:
            return 0.75
        if "infrastructure" in normalized:
            return 0.7
        return 0.8


def _safe_float(value: Any) -> float | None:
    try:
        if value is None:
            return None
        return float(value)
    except (TypeError, ValueError):
        return None


def _safe_datetime(value: Any) -> datetime:
    if isinstance(value, datetime):
        if value.tzinfo is None:
            return value.replace(tzinfo=timezone.utc)
        return value.astimezone(timezone.utc)
    if isinstance(value, str):
        try:
            parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
            if parsed.tzinfo is None:
                return parsed.replace(tzinfo=timezone.utc)
            return parsed.astimezone(timezone.utc)
        except ValueError:
            pass
    return datetime.now(timezone.utc)
