from pathlib import Path
from typing import Any, Dict, Optional, Tuple

import geopandas as gpd

try:  # Reuse the spatial index implementation from the data pipeline.
    from logic.api import SafetyMapIndex, OUTPUT_PATH
except ImportError:  # pragma: no cover
    # Fallback import path when running with different PYTHONPATH settings.
    from logic.api import SafetyMapIndex, OUTPUT_PATH  # type: ignore


_safety_index: Optional[SafetyMapIndex] = None


def _load_safety_index() -> SafetyMapIndex:
    """
    Lazily loads the precomputed safety dataset and builds a spatial index.

    The dataset is generated by the spatial pipeline in `logic/` and exported
    as a GeoJSON file at `OUTPUT_PATH`.
    """
    global _safety_index

    if _safety_index is not None:
        return _safety_index

    dataset_path = Path(OUTPUT_PATH)
    if not dataset_path.exists():
        raise RuntimeError(
            f"Safety dataset not found at {dataset_path}. "
            "Run the spatial data pipeline to generate it."
        )

    segments_gdf = gpd.read_file(dataset_path)
    _safety_index = SafetyMapIndex(segments_gdf)
    return _safety_index


def nearest_segment(lat: float, lon: float) -> Tuple[Dict[str, Any], float]:
    """
    Returns the nearest safety segment and metric distance to the query point.
    """
    index = _load_safety_index()
    return index.nearest_segment(lat=lat, lon=lon)

